create table TEAMS (
    yearID INTEGER,
    lgID TEXT(2),
    teamID TEXT(3) PRIMARY KEY,
    franchID TEXT(3),
    divID TEXT(1),
    Rank INTEGER,
    G INTEGER,
    Ghome INTEGER,
    W INTEGER,
    L INTEGER,
    DivWin TEXT(1),
    WCWin TEXT(1),
    LgWin TEXT(1),
    WSWin TEXT(1),
    R INTEGER,
    AB INTEGER,
    H INTEGER,
    '2B' INTEGER,
    '3B' INTEGER,
    HR INTEGER,
    BB INTEGER,
    SO INTEGER,
    SB INTEGER,
    CS INTEGER,
    HBP INTEGER,
    SF INTEGER,
    RA INTEGER,
    ER INTEGER,
    ERA REAL,
    CG INTEGER,
    SHO INTEGER,
    SV INTEGER,
    IPouts INTEGER,
    HA INTEGER,
    HRA INTEGER,
    BBA INTEGER,
    SOA INTEGER,
    E INTEGER,
    DP INTEGER,
    FP REAL,
    name TEXT(100),
    park TEXT(100) REFERENCES PARKS ([park.name]),
    attendance INTEGER,
    BPF INTEGER,
    PPF INTEGER,
    teamIDBR TEXT(3),
    teamIDIahman45 TEXT(3),
    teamIDretro TEXT(3)
)

select * from TEAMS

create table PARKS (
    'park.key' TEXT(6) PRIMARY KEY,
    'park.name' TEXT(100),
    'park.alias' TEXT(300),
    city TEXT(100),
    state TEXT(100),
    country TEXT(2)
)

create table PEOPLE (
    playerID TEXT,
    birthYear INTEGER,
    birthMonth INTEGER,
    birthDay INTEGER,
    birthCountry TEXT(3),
    birthState TEXT(100),
    birthCity TEXT(100),
    deathYear INTEGER,
    deathMonth INTEGER,
    deathDay INTEGER,
    deathCountry TEXT(3),
    deathState TEXT(2),
    deathCity TEXT(100),
    nameFirst TEXT(100),
    nameLast TEXT(100),
    nameGiven TEXT(100),
    weight INTEGER,
    height INTEGER,
    bats TEXT(1),
    throws TEXT(1),
    debut DATE,
    finalGame DATE,
    retroID	TEXT(10),
    bbrefID	TEXT(10)
)

CREATE TABLE BATTING (
    playerID TEXT REFERENCES PEOPLE (playerID),
    yearID INTEGER,
    stint INTEGER,
    teamID TEXT REFERENCES TEAMS (teamID),
    lgID TEXT,
    G INTEGER,
    AB INTEGER,
    R INTEGER,
    H INTEGER,
    [2B] INTEGER,
    [3B] INTEGER,
    HR INTEGER,
    RBI INTEGER,
    SB INTEGER,
    CS INTEGER,
    BB INTEGER,
    SO INTEGER,
    IBB INTEGER,
    HBP INTEGER,
    SH INTEGER,
    SF INTEGER,
    GIDP INTEGER
)